spring:
  application:
    name: screener

  data:
    mongodb:
      host: localhost
      port: 27017
      database: stock_screener
  shell:
    interactive:
      enabled: true
#    script:
#      enabled: true



fmp:
    api:
      apiKey: jJRhiQp3yj4GsLa7dYNsGC36VUbm3IYV
      base-url: https://financialmodelingprep.com/stable



logging:
  level:
    com:
      example:
            stockscreener: INFO
    org:
      springframework:
                data:
                  mongodb: INFO